fs = require 'fs'
require 'coffee-script/register'
Rehab = require '../src/rehab'

# Make sure output directory is available
try fs.mkdirSync 'bin'

task 'build:coffee', 'Compile coffee-script using Rehab', ->
  rehab = new Rehab('./coffee')
  console.log rehab.listFiles()
  fs.writeFileSync 'bin/compiled-coffeescript.js', rehab.compile()

task 'build:styl', 'Compile stylus files using Rehab', ->
  rehab = new Rehab('./styl')
  console.log rehab.listFiles()
  fs.writeFileSync 'bin/compiled-stylus.css', rehab.compile()