// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    coffee: function(contents) {
      var coffee;
      coffee = require('coffee-script');
      return coffee.compile(contents);
    }
  };

}).call(this);
