// Generated by CoffeeScript 1.7.1
(function() {
  var cm, pathMatch, token, type;

  pathMatch = function(ext) {
    return "\\s*_require\\s+(.+)\\s*";
  };

  token = function(ext) {
    return RegExp("^\\s*" + cm[ext].open + (pathMatch(ext)) + cm[ext].close + "\\s*$", "i");
  };

  module.exports = function(ext) {
    ext = ext.toUpperCase();
    if (cm[ext] == null) {
      console.error("Cannot parse files of type:" + ext);
      return null;
    } else {
      return token(ext);
    }
  };

  type = {
    sa: {
      open: '/\\*',
      close: '\\*/'
    },
    ds: {
      open: '//',
      close: ''
    },
    hash: {
      open: '#',
      close: ''
    }
  };

  cm = {
    "STYL": type.ds,
    "CSS": type.ds,
    "LESS": type.ds,
    "SASS": type.ds,
    "RB": type.hash,
    "JS": type.ds,
    "COFFEE": type.hash
  };

}).call(this);
